name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  BACKEND_IMAGE: fnatikjk/welltracker-backend:last
  BACKEND_DOCKER_LOGIN: fnatikjk
  BACKEND_TG_WORKER_IMAGE: fnatikjk2/welltracker-tg-worker:last
  BACKEND_TG_WORKER_DOCKER_LOGIN: fnatikjk2
  BACKEND_NOTIFICATIONS_WORKER_IMAGE: fnatikjk3/welltracker-notifications-worker:last
  BACKEND_NOTIFICATIONS_WORKER_DOCKER_LOGIN: fnatikjk3
  FRONTEND_IMAGE: iceneo/welltracker-frontend:last
  FRONTEND_DOCKER_LOGIN: iceneo

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_LOGIN: ${{ env.BACKEND_DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_BACKEND }}
      run:
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ env.BACKEND_IMAGE }}
      run: |
        cd ./API
        docker build -f Dockerfile --force-rm -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  build-tg-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_LOGIN: ${{ env.BACKEND_TG_WORKER_DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.BACKEND_TG_WORKER_DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ env.BACKEND_TG_WORKER_IMAGE }}
      run: |
        cd ./API
        docker build -f Dockerfile.TelegramBotWorker --force-rm -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  build-notifications-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_LOGIN: ${{ env.BACKEND_NOTIFICATIONS_WORKER_DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.BACKEND_NOTIFICATIONS_WORKER_DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ env.BACKEND_NOTIFICATIONS_WORKER_IMAGE }}
      run: |
        cd ./API
        docker build -f Dockerfile.NotificationsWorker --force-rm -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_LOGIN: ${{ env.FRONTEND_DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.FRONTEND_DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ env.FRONTEND_IMAGE }}
      run: |
        cd ./client
        docker build -f Dockerfile --force-rm -t $IMAGE_TAG .
        docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest

    needs: ["build-backend", "build-frontend"]

    steps:
    - name: Run docker compose
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.VPS_HOST }}
        username: ${{ vars.SSH_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd deploy
          sudo sh compose.sh
